sudo: false

git:
  depth: 1

language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"

matrix:
  fast_finish: true

branches:
  only:
    - master

install:
  - npm install

before_script:
  - node --version
  - npm --version
  - npm run build

script:
  - npm test
